---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Blog
- type: document
  path: Blog
  label: Posts
- type: directory
  path: Blog
  label: Blog Section
  create: all
  match: "**/*"
  new_doc_ext: ".md"
upload_dir: uploads
public_path: "/public/blog"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
