import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Suhas Kashyap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>BRUH THIS TOOK SO LONG TO FIGURE OUT</h1>
        <ul>
          <li>
            wsl is pretty cool but use{" "}
            <pre>\\wsl$\Ubuntu-20.04\home\kashyap\__workspace\git</pre> Hot
            reload won't work otherwise
          </li>
          <li>
            in godaddy domain config set cname - host as www then value as the
            dns target generated from heroku
          </li>
          <li>
            non www sites are not supported by the free SSL cert signing thingy.
            Unsafe naked http://kashyapsuhas.com
          </li>
          <li>Send me good personal site examples please thanks</li>
          <li>
            I actually quite like Pineapple on pizza. When it's sliced thin and
            charred nicely it's awesome.
          </li>
        </ul>
      </main>
    </div>
  );
}
