// the ganita core is checked against swiss ephemeris, not against itself.
//
// fixtures/swisseph-reference.json is generated by scripts/gen-jyotisha-fixtures.py
// (pyswisseph, moshier ephemeris, SIDM_LAHIRI). regenerate it if you change the
// sampled dates; do not hand-edit it.
//
// tolerances are in arcseconds and are deliberately just above the measured worst
// case. if a change makes one of these fail, the change moved the astronomy.
import { signedDiff } from "../angles";
import { ayanamsaAt } from "../ayanamsa";
import { buildChart, lagnaLongitude, vargaRashi } from "../chart";
import { grahaPositions } from "../ephemeris";
import type { GrahaId } from "../types";
import reference from "./fixtures/swisseph-reference.json";

const asArcsec = (deg: number) => deg * 3600;

const dateOf = (iso: string) => new Date(iso);

/** worst absolute difference in arcsec across every sample. */
function worstOf<T>(items: T[], diff: (item: T) => number): number {
  return items.reduce((max, item) => Math.max(max, Math.abs(diff(item))), 0);
}

describe("lahiri ayanamsa", () => {
  it("matches swiss ephemeris to under an arcsecond, 1900-2050", () => {
    const worst = worstOf(reference.ayanamsa, (a) =>
      asArcsec(ayanamsaAt(dateOf(a.iso)) - a.deg),
    );
    expect(worst).toBeLessThan(1);
  });

  it("beats a linear fit by two orders of magnitude", () => {
    // the naive approximation this replaced, kept as a regression guard so nobody
    // "simplifies" the ayanamsa back into a straight line
    const linear = (jd: number) => 23.853 + 0.01396 * ((jd - 2451545) / 365.25);
    const worstLinear = worstOf(reference.ayanamsa, (a) =>
      asArcsec(linear(a.jd_ut) - a.deg),
    );
    const worstOurs = worstOf(reference.ayanamsa, (a) =>
      asArcsec(ayanamsaAt(dateOf(a.iso)) - a.deg),
    );
    expect(worstLinear).toBeGreaterThan(25);
    expect(worstOurs).toBeLessThan(worstLinear / 100);
  });

  it("increases monotonically", () => {
    // precession only runs one way. a sign slip here is silent and catastrophic.
    const values = reference.ayanamsa.map((a) => ayanamsaAt(dateOf(a.iso)));
    for (let i = 1; i < values.length; i++) {
      expect(values[i]).toBeGreaterThan(values[i - 1]);
    }
  });
});

describe("graha positions", () => {
  const physical: GrahaId[] = [
    "surya",
    "chandra",
    "budha",
    "shukra",
    "kuja",
    "guru",
    "shani",
  ];

  it.each(physical)("%s matches swiss ephemeris within 15 arcsec", (graha) => {
    const worst = worstOf(reference.grahas, (epoch) => {
      const ours = grahaPositions(dateOf(epoch.iso))[graha].lon;
      const theirs = (epoch.positions as Record<string, { lon: number }>)[graha]
        .lon;
      return asArcsec(signedDiff(ours, theirs));
    });
    expect(worst).toBeLessThan(15);
  });

  it("uses the mean node for rahu, referred to the true equinox", () => {
    const worst = worstOf(reference.grahas, (epoch) => {
      const ours = grahaPositions(dateOf(epoch.iso), { node: "mean" }).rahu.lon;
      return asArcsec(signedDiff(ours, epoch.positions.rahu_mean.lon));
    });
    expect(worst).toBeLessThan(1);
  });

  it("does not silently use the true node", () => {
    // mean and true differ by over a degree, enough to move rahu into another
    // nakshatra. this guards the default, which indian panchangas require to be mean.
    const worst = worstOf(reference.grahas, (epoch) =>
      asArcsec(
        signedDiff(
          epoch.positions.rahu_true.lon,
          epoch.positions.rahu_mean.lon,
        ),
      ),
    );
    expect(worst).toBeGreaterThan(1800); // > 0.5 degrees somewhere in the sample
  });

  it("places ketu exactly opposite rahu", () => {
    const worst = worstOf(reference.grahas, (epoch) => {
      const g = grahaPositions(dateOf(epoch.iso));
      return asArcsec(signedDiff(g.ketu.lon, g.rahu.lon + 180));
    });
    expect(worst).toBeLessThan(0.001);
  });

  it("reports the nodes as vakri", () => {
    const g = grahaPositions(new Date("2000-01-01T12:00:00Z"));
    expect(g.rahu.vakri).toBe(true);
    expect(g.ketu.vakri).toBe(true);
    expect(g.rahu.speed).toBeLessThan(0);
  });

  it("derives speed with the right sign and magnitude", () => {
    const worst = worstOf(reference.grahas, (epoch) => {
      const ours = grahaPositions(dateOf(epoch.iso)).chandra.speed;
      return (ours - epoch.positions.chandra.speed) * 3600;
    });
    // chandra moves 11.8-15.4 deg/day; 1 arcsec/day of agreement is plenty
    expect(worst).toBeLessThan(1);
  });

  it("catches shani vakri at j2000", () => {
    // swisseph has shani at -0.0199 deg/day on 2000-01-01, i.e. retrograde
    const g = grahaPositions(new Date("2000-01-01T12:00:00Z"));
    expect(g.shani.vakri).toBe(true);
    expect(g.surya.vakri).toBe(false);
  });
});

describe("lagna", () => {
  it("matches swiss ephemeris within 5 arcsec across latitudes", () => {
    const worst = worstOf(reference.lagna, (l) => {
      const ours = lagnaLongitude({
        when: dateOf(l.iso),
        latitude: l.lat,
        longitude: l.lon,
      });
      return asArcsec(signedDiff(ours, l.ascendant));
    });
    expect(worst).toBeLessThan(5);
  });

  it("is sensitive to birth time the way a real chart is", () => {
    // ~1 degree of lagna per 4 minutes. this is why birth time matters so much and
    // why a chart from a remembered "around 6 in the morning" is soft.
    const base = { latitude: 12.9716, longitude: 77.5946 };
    const a = lagnaLongitude({
      ...base,
      when: new Date("1990-05-01T00:30:00Z"),
    });
    const b = lagnaLongitude({
      ...base,
      when: new Date("1990-05-01T00:34:00Z"),
    });
    expect(Math.abs(signedDiff(a, b))).toBeGreaterThan(0.5);
    expect(Math.abs(signedDiff(a, b))).toBeLessThan(1.5);
  });
});

describe("bhavas", () => {
  it("puts the lagna rashi in the first bhava under whole sign", () => {
    const chart = buildChart({
      when: new Date("1990-05-01T00:30:00Z"),
      latitude: 12.9716,
      longitude: 77.5946,
    });
    expect(chart.bhavaRashi[0]).toBe(chart.lagna.rashi);
    expect(chart.bhavaRashi).toHaveLength(12);
    expect(new Set(chart.bhavaRashi).size).toBe(12);
  });

  it("assigns each graha a bhava consistent with its rashi", () => {
    const chart = buildChart({
      when: new Date("1990-05-01T00:30:00Z"),
      latitude: 12.9716,
      longitude: 77.5946,
    });
    for (const [id, pos] of Object.entries(chart.grahas)) {
      const expected = ((pos.rashi - chart.lagna.rashi + 12) % 12) + 1;
      expect(chart.bhava[id as GrahaId]).toBe(expected);
    }
  });
});

describe("vargas", () => {
  it("D1 is just the rashi", () => {
    expect(vargaRashi(0, "D1")).toBe(0);
    expect(vargaRashi(35, "D1")).toBe(1);
    expect(vargaRashi(359.99, "D1")).toBe(11);
  });

  it("D9 continuous formula equals the classical starting-sign rule", () => {
    // chara signs start the navamsa from themselves, sthira from the 9th, dvisvabhava
    // from the 5th. if these agree at every one of the 108 navamsas, the shortcut is
    // safe to keep.
    const startOffset = [0, 8, 4]; // chara, sthira, dvisvabhava
    for (let rashi = 0; rashi < 12; rashi++) {
      const swabhava = rashi % 3; // 0 chara, 1 sthira, 2 dvisvabhava
      for (let part = 0; part < 9; part++) {
        const lon = rashi * 30 + part * (30 / 9) + 0.5;
        const classical = (rashi + startOffset[swabhava] + part) % 12;
        expect(vargaRashi(lon, "D9")).toBe(classical);
      }
    }
  });

  it("D2 splits each rashi into simha and kataka horas", () => {
    expect(vargaRashi(5, "D2")).toBe(4); // mesha first half -> simha
    expect(vargaRashi(20, "D2")).toBe(3); // mesha second half -> kataka
    expect(vargaRashi(35, "D2")).toBe(3); // vrishabha first half -> kataka
    expect(vargaRashi(50, "D2")).toBe(4); // vrishabha second half -> simha
  });

  it("D3 gives the 1st, 5th and 9th from the sign", () => {
    expect(vargaRashi(5, "D3")).toBe(0); // mesha
    expect(vargaRashi(15, "D3")).toBe(4); // simha, 5th from mesha
    expect(vargaRashi(25, "D3")).toBe(8); // dhanu, 9th from mesha
  });

  it("D30 uses the unequal split and reverses it for even signs", () => {
    expect(vargaRashi(3, "D30")).toBe(0); // mesha 0-5 -> kuja
    expect(vargaRashi(7, "D30")).toBe(10); // mesha 5-10 -> shani
    expect(vargaRashi(28, "D30")).toBe(6); // mesha 25-30 -> shukra
    expect(vargaRashi(33, "D30")).toBe(1); // vrishabha 0-5 -> shukra
    expect(vargaRashi(59, "D30")).toBe(7); // vrishabha 25-30 -> kuja
  });

  it("every varga returns a valid rashi for every longitude", () => {
    const ids = ["D1", "D2", "D3", "D9", "D10", "D12", "D30", "D60"] as const;
    for (const id of ids) {
      for (let lon = 0; lon < 360; lon += 0.37) {
        const r = vargaRashi(lon, id);
        expect(Number.isInteger(r)).toBe(true);
        expect(r).toBeGreaterThanOrEqual(0);
        expect(r).toBeLessThan(12);
      }
    }
  });
});

describe("nakshatra and pada", () => {
  it("divides the zodiac into 27 nakshatras of 4 padas", () => {
    const g = grahaPositions(new Date("2000-01-01T12:00:00Z"));
    for (const pos of Object.values(g)) {
      expect(pos.nakshatra).toBeGreaterThanOrEqual(0);
      expect(pos.nakshatra).toBeLessThan(27);
      expect(pos.pada).toBeGreaterThanOrEqual(1);
      expect(pos.pada).toBeLessThanOrEqual(4);
      expect(pos.rashi).toBe(Math.floor(pos.lon / 30));
    }
  });

  it("agrees with swiss ephemeris on which nakshatra chandra is in", () => {
    // the single most consequential derived value in a chart: it sets the vimshottari
    // dasha balance at birth.
    for (const epoch of reference.grahas) {
      const ours = grahaPositions(dateOf(epoch.iso)).chandra;
      const theirs = Math.floor(epoch.positions.chandra.lon / (360 / 27));
      expect(ours.nakshatra).toBe(theirs);
    }
  });
});

export {};
